config/routes.rb
Rails.application.routes.draw do

  resources :slides
  get 'styleguide' => 'styleguide#index' if Rails.env.development?
  resources :social_bodies
  resources :social_bodies
  resources :chapters
  resources :fees
  resources :private_informations
  resources :laws
  get 'styleguide' => 'styleguide#index' if Rails.env.development?

  get 'admin_members/show/:id', to: 'admin_members#show', as: 'admin_member_show'
  get 'admin_members/edit/:id', to: 'admin_members#edit', as: 'admin_member_edit'
  get 'admin_members/new', to: 'admin_members#new', as: 'admin_member_new'
  patch 'admin_members/update/:id', to: 'admin_members#update', as: 'admin_update_member'
  post 'admin_members/create', to: 'admin_members#create', as: 'admin_create_member'
  delete 'admin_members/destroy/:id', to: 'admin_members#destroy', as: 'admin_destroy_member'
  get 'admin_members/index_pending', to: 'admin_members#index_pending', as: 'index_pending'
  get 'admin_members/index_active', to: 'admin_members#index_active', as: 'index_active'

  resources :protocols, only: [:show, :edit]
  resources :categories
  resources :benefits
  resources :abouts
  resources :jobs
  resources :partners
  resources :posts
  as :member do
    patch '/members/confirmation' => 'members/confirmations#update', :via => :patch, :as => :update_member_confirmation
  end

  devise_for :members, controllers: { confirmations: "members/confirmations"}

  get 'general_pages/about', to: 'general_pages#about', as: 'gp_about'
  get 'general_pages/news', to: 'general_pages#news', as: 'gp_news'
  get 'general_pages/benefits', to: 'general_pages#benefits', as: 'gp_benefits'
  get 'general_pages/contact', to: 'general_pages#contact', as: 'gp_contact'
  post 'general_pages/send_contact', to: 'general_pages#send_contact', as: 'gp_send_contact'

  get 'general_pages/partners', to: 'general_pages#partners', as: 'gp_partners'
  get 'general_pages/jobs', to: 'general_pages#jobs', as: 'gp_jobs'

  get 'general_pages/post/:id', to: 'general_pages#post', as: 'gp_post'
  get 'general_pages/job/:id', to: 'general_pages#job', as: 'gp_job'
  get 'general_pages/benefit/:id', to: 'general_pages#benefit', as: 'gp_benefit'
  get 'general_pages/protocol/:id', to: 'general_pages#protocol', as: 'gp_protocol'
  get 'general_pages/statutes', to: 'general_pages#statutes', as: 'gp_statutes'
  get 'general_pages/laws', to: 'general_pages#laws', as: 'gp_laws'
  get 'general_pages/social_bodies', to: 'general_pages#social_bodies', as: 'gp_social_bodies'
  get 'general_pages/private_informations', to: 'general_pages#private_informations', as: 'gp_private_informations'
  get 'general_pages/profile', to: 'general_pages#profile', as: 'gp_profile'
  root 'general_pages#index'

  get 'admin', to: 'admin_members#index_active', as: 'admin_root'

end

app/controllers/admin_members_controller.rb
class AdminMembersController < ApplicationController

  before_action :authenticate_member!

  before_action :authenticate_admin

  before_action :set_member, only: [:show, :edit, :update, :destroy]

  include MembersHelper
  def index_active
    if params[:search]
      @members = Kaminari.paginate_array(Member.where.not(role: role_pending).search(params[:search])).page(params[:page]).per(30)
    else
      @members = Member.where.not(role: role_pending).page(params[:page]).per(30)
    end
  end


  def index_pending
    if params[:search]
      @members = Kaminari.paginate_array(Member.where(role: role_pending).search(params[:search])).page(params[:page]).per(30)
    else
      @members = Member.where(role: role_pending).page(params[:page]).per(30)
    end
  end

  def show
  end

  def edit
  end

  def new
    @member = Member.new
  end

  def create
    respond_to do |format|
      @member = Member.new(member_params)

      if @member.save
        @member.send_confirmation_instructions
        format.html { redirect_to admin_member_show_path(@member), notice: 'Member was successfully created.' }
        # format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :new }
        # format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to admin_member_show_path(@member), notice: 'Member was successfully updated.' }
        # format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        # format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Member was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def member_params
    params.require(:member).permit(:name, :membership_number, :email, :naturality, :birthday, :residence, :zip_code, :phone, :office, :office_address, :office_zipcode, :attached_registry, :office_phone, :office_fax, :location_class, :career_start_date, :personal_class, :class_promotion_date, :practice_level, :level_start_date, :pending, :role)
  end

  def authenticate_admin
    if !current_member.is_admin?
      redirect_to root_path, notice: "You are no admin!"
    else
    end
  end

end

app/helpers/admin_members_helper.rb
module AdminMembersHelper
end

app/views/admin_members/edit.html.erb
<%= render partial: 'admin_partials/edit/header', locals: { section_title: t("controller."+params[:controller]),
                                                  section_sub_title: t("action."+params[:action]),
                                                  page_title: t("strings.member.edit") } %>
        <div class="box-body">
          <%= form_for(@member, url: admin_update_member_path(@member)) do |f| %>

            <%= render partial: 'admin_partials/errors/errors_form', locals: { current_object: @member} %>


          <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name, class: "form-control", required: true  %>
          </div>

          <div class="form-group">
            <%= f.label :membership_number %><br>
            <%= f.number_field :membership_number, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :email %><br>
            <%= f.email_field :email, class: "form-control", required: true %>
          </div>

          <div class="form-group">
            <%= f.label :birthday %><br>
            <%= f.text_field :birthday, class: "form-control", id: 'birthday', data: { date_format: 'yyyy-mm-dd'} %>
          </div>

          <div class="form-group">
            <%= f.label :naturality %><br>
            <%= f.text_field :naturality, class: "form-control", required: true  %>
          </div>

          <div class="form-group">
            <%= f.label :residence %><br>
            <%= f.text_area :residence, class: "form-control", required: true  %>
          </div>

          <div class="form-group">
            <%= f.label :zip_code %><br>
            <%= f.text_field :zip_code, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :phone %><br>
            <%= f.text_field :phone, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :office %><br>
            <%= f.text_field :office, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :office_address %><br>
            <%= f.text_field :office_address, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :office_zipcode %><br>
            <%= f.text_field :office_zipcode, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :attached_registry %><br>
            <%= f.check_box :attached_registry %>
          </div>

          <div class="form-group">
            <%= f.label :office_phone %><br>
            <%= f.text_field :office_phone, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :office_fax %><br>
            <%= f.text_field :office_fax, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :location_class %><br>
            <%= f.text_field :location_class, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :career_start_date %><br>
            <%= f.text_field :career_start_date, class: "form-control", id: 'career_start_date', data: { date_format: 'yyyy-mm-dd'} %>
          </div>

          <div class="form-group">
            <%= f.label :personal_class %><br>
            <%= f.text_field :personal_class, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :class_promotion_date %><br>
            <%= f.text_field :class_promotion_date, class: "form-control", id: 'class-promotion-date', data: { date_format: 'yyyy-mm-dd'} %>
          </div>

          <div class="form-group">
            <%= f.label :practice_level %><br>
            <%= f.text_field :practice_level, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :level_start_date %><br>
            <%= f.text_field :level_start_date, class: "form-control", id: 'level-start-date', data: { date_format: 'yyyy-mm-dd'} %>
          </div>

          <div class="form-group">
            <%= f.label :role %><br>
            <%= f.select :role, options_for_select(get_roles_options(), @member.role.to_s), {}, class: "form-control" %>
          </div>



          <div class="box-footer">
            <%= f.submit class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>

      <%= render partial: 'admin_partials/edit/footer', locals: {object_to_show: nil, back_path: :back}%>

      <!-- <div class="box-footer">
        <%#= link_to 'Ver', @member %> |
        <%= link_to 'Voltar', :back %>
      </div> -->

    <!-- </div>
  </div>
</section> -->

<script>
$(document).on("ready page:load", function () {
  $('#birthday').datepicker(
  {
    todayHighlight: true,
    autoclose: true
  });
  $('#career-start-date').datepicker(
  {
    todayHighlight: true,
    autoclose: true
  });
  $('#class-promotion-date').datepicker(
  {
    todayHighlight: true,
    autoclose: true
  });
  $('#level-start-date').datepicker(
  {
    todayHighlight: true,
    autoclose: true
  });
});
</script>

app/views/admin_members/index_active.html.erb
<%= render partial: 'admin_partials/index/header', locals: { section_title: t("controller."+params[:controller]),
                                                  section_sub_title: t("action."+params[:action]),
                                                  page_title: t("strings.member.listing"),
                                                  new_path: admin_member_new_path,
                                                  new_button_name: t("strings.member.new"),
                                                  search_form_path: index_active_path } %>

<%= render "admin_partials/errors/notices" %>


        <div class="box-body table-responsive no-padding">
          <%= render 'layouts/admin_notices' %>
          <table class="table table-hover">
            <thead>
              <tr>
                <th><%= t 'activerecord.attributes.member.name' %> </th>
                <th><%= t 'activerecord.attributes.member.email' %></th>
                <th><%= t 'activerecord.attributes.member.membership_number' %></th>
                <th><%= t 'activerecord.attributes.member.role' %></th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @members.each do |member| %>
                <tr>
                  <td><%= member.name %></td>
                  <td><%= member.email %></td>
                  <td><%= member.membership_number %></td>
                  <td><%= get_role(member.role) %></td>
                  <td>
                    <div class="btn-group">
                      <%= link_to  t('strings.admin.show'), admin_member_show_path(member), class:"btn btn-info" %>
                      <%= link_to  t('strings.admin.edit'), admin_member_edit_path(member), class:"btn btn-info" %>
                      <%= link_to  t('strings.admin.destroy'), admin_destroy_member_path(member), method: :delete, data: { confirm: t('strings.admin.are_you_sure') }, class:"btn btn-info" %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div><!-- /.box-body -->
        <%= render partial: 'admin_partials/index/footer', locals: { paginate_object: @members} %>

app/views/admin_members/index_pending.html.erb
<%= render partial: 'admin_partials/index/header', locals: { section_title: t("controller."+params[:controller]),
                                                  section_sub_title: t("action."+params[:action]),
                                                  page_title: t("strings.member.listing"),
                                                  new_path: admin_member_new_path,
                                                  new_button_name: t("strings.member.new"),
                                                  search_form_path: index_pending_path } %>

<%= render "admin_partials/errors/notices" %>


        <div class="box-body table-responsive no-padding">
          <%= render 'layouts/admin_notices' %>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Email</th>
                <th>Número de Sócio</th>
                <th>Função</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @members.each do |member| %>
                <tr>
                  <td><%= member.name %></td>
                  <td><%= member.email %></td>
                  <td><%= member.membership_number %></td>
                  <td><%= get_role(member.role) %></td>
                  <td>
                    <div class="btn-group">
                      <%= link_to  t("strings.admin.show"), admin_member_show_path(member), class:"btn btn-info" %>
                      <%= link_to  t("strings.admin.edit"), admin_member_edit_path(member), class:"btn btn-info" %>
                      <%= link_to  t("strings.admin.destroy"), admin_destroy_member_path(member), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-info" %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div><!-- /.box-body -->
        <div class="box-footer clearfix">
          <ul class="pagination pagination-sm no-margin pull-right">
            <%= paginate @members, :theme => 'twitter-bootstrap-3' %>
          </ul>
        </div>
      </div><!-- /.box -->
    </div>
  </div>
</section>

app/views/admin_members/new.html.erb
<%= render partial: 'admin_partials/new/header', locals: { section_title: t("controller."+params[:controller]),
                                                  section_sub_title: t("action."+params[:action]),
                                                  page_title: t("strings.member.new") } %>
        <div class="box-body">

          <%= form_for(@member, url: admin_create_member_path) do |f| %>
            <%= render partial: 'admin_partials/errors/errors_form', locals: { current_object: @member} %>

            <div class="form-group">
              <%= f.label :email %>*<br />
              <%= f.email_field :email, class: "form-control", autofocus: true, required: true %>
            </div>
            <div class="form-group">
              <%= f.label :name %>*<br>
              <%= f.text_field :name, class: "form-control", required: true  %>
            </div>

            <div class="form-group">
              <%= f.label :membership_number %><br>
              <%= f.number_field :membership_number, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :birthday %><br>
              <%= f.text_field :birthday, class: "form-control", id: 'birthday', data: { date_format: 'yyyy-mm-dd'} %>
            </div>

            <div class="form-group">
              <%= f.label :naturality%>*<br>
              <%= f.text_field :naturality, class: "form-control", required: true  %>
            </div>

            <div class="form-group">
              <%= f.label :residence %>*<br>
              <%= f.text_area :residence, class: "form-control", required: true  %>
            </div>

            <div class="form-group">
              <%= f.label :zip_code%><br>
              <%= f.text_field :zip_code, class: "form-control"%>
            </div>

            <div class="form-group">
              <%= f.label :phone %><br>
              <%= f.text_field :phone, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :office %>*<br>
              <%= f.text_field :office, class: "form-control", required: true %>
            </div>

            <div class="form-group">
              <%= f.label :office_address %>*<br>
              <%= f.text_field :office_address, class: "form-control", required: true %>
            </div>

            <div class="form-group">
              <%= f.label :office_zipcode %>*<br>
              <%= f.text_field :office_zipcode, class: "form-control", required: true %>
            </div>

            <div class="form-group">
              <%= f.label :attached_registry %>*<br>
              <%= f.check_box :attached_registry %>
            </div>

            <div class="form-group">
              <%= f.label :office_phone %>*<br>
              <%= f.text_field :office_phone, class: "form-control", required: true %>
            </div>

            <div class="form-group">
              <%= f.label :office_fax %><br>
              <%= f.text_field :office_fax, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :location_class %>*<br>
              <%= f.text_field :location_class, class: "form-control", required: true %>
            </div>

            <div class="form-group">
              <%= f.label :career_start_date %><br>
              <%= f.text_field :career_start_date, class: "form-control", id: "career-start-date", data: { date_format: 'yyyy-mm-dd'} %>
            </div>

            <div class="form-group">
              <%= f.label :personal_class %>*<br>
              <%= f.text_field :personal_class, class: "form-control", required: true %>
            </div>

            <div class="form-group">
              <%= f.label :class_promotion_date %><br>
              <%= f.text_field :class_promotion_date, class: "form-control", id: "class-promotion-date", data: { date_format: 'yyyy-mm-dd'} %>
            </div>

            <div class="form-group">
              <%= f.label :practice_level %>*<br>
              <%= f.text_field :practice_level, class: "form-control", required: true %>
            </div>

            <div class="form-group">
              <%= f.label :level_start_date %><br>
              <%= f.text_field :level_start_date, class: "form-control", id: "level-start-date", data: { date_format: 'yyyy-mm-dd'} %>
            </div>

            <div class="box-footer">
              <%= f.submit class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
        <%= render partial: 'admin_partials/new/footer', locals: { back_path: :back}%>






<script>
$(document).on("ready page:load", function () {
  $('#birthday').datepicker(
  {
    todayHighlight: true,
    autoclose: true
  });
  $('#career-start-date').datepicker(
  {
    todayHighlight: true,
    autoclose: true
  });
  $('#class-promotion-date').datepicker(
  {
    todayHighlight: true,
    autoclose: true
  });
  $('#level-start-date').datepicker(
  {
    todayHighlight: true,
    autoclose: true
  });
});
</script>

app/views/admin_members/show.html.erb
<%= render partial: 'admin_partials/show/header', locals: { section_title: t("controller."+params[:controller]),
                                                  section_sub_title: t("action."+params[:action]),
                                                  page_title: t("strings.member.show") } %>

<%= render "admin_partials/errors/notices" %>


          <strong><%= t 'activerecord.attributes.member.name' %></strong>
          <p class="text-muted">
            <%= @member.name %>
          </p>

          <strong><%= t 'activerecord.attributes.member.membership_number' %></strong>
          <p class="text-muted">
            <%= @member.membership_number %>
          </p>

          <strong><%= t 'activerecord.attributes.member.email' %></strong>
          <p class="text-muted">
            <%= @member.email %>
          </p>

          <strong><%= t 'activerecord.attributes.member.naturality' %></strong>
          <p class="text-muted">
            <%= @member.naturality %>
          </p>

          <strong><%= t 'activerecord.attributes.member.birthday' %></strong>
          <p class="text-muted">
            <%= @member.birthday %>
          </p>

          <strong><%= t 'activerecord.attributes.member.residence' %></strong>
          <p class="text-muted">
            <%= @member.residence %>
          </p>

          <strong><%= t 'activerecord.attributes.member.zip_code' %></strong>
          <p class="text-muted">
            <%= @member.zip_code %>
          </p>

          <strong><%= t 'activerecord.attributes.member.phone' %></strong>
          <p class="text-muted">
            <%= @member.phone %>
          </p>

          <strong><%= t 'activerecord.attributes.member.office' %></strong>
          <p class="text-muted">
            <%= @member.office %>
          </p>

          <strong><%= t 'activerecord.attributes.member.office_email' %></strong>
          <p class="text-muted">
            <%= @member.office_email %>
          </p>

          <strong><%= t 'activerecord.attributes.member.office_address' %></strong>
          <p class="text-muted">
            <%= @member.office_address %>
          </p>

          <strong><%= t 'activerecord.attributes.member.office_zipcode' %></strong>
          <p class="text-muted">
            <%= @member.office_zipcode %>
          </p>

          <strong><%= t 'activerecord.attributes.member.attached_registry' %></strong>
          <p class="text-muted">
            <%= @member.attached_registry %>
          </p>

          <strong><%= t 'activerecord.attributes.member.office_phone' %></strong>
          <p class="text-muted">
            <%= @member.office_phone %>
          </p>

          <strong><%= t 'activerecord.attributes.member.office_fax' %></strong>
          <p class="text-muted">
            <%= @member.office_fax %>
          </p>

          <strong><%= t 'activerecord.attributes.member.location_class' %></strong>
          <p class="text-muted">
            <%= @member.location_class %>
          </p>

          <strong><%= t 'activerecord.attributes.member.career_start_date' %></strong>
          <p class="text-muted">
            <%= @member.career_start_date %>
          </p>

          <strong><%= t 'activerecord.attributes.member.personal_class' %></strong>
          <p class="text-muted">
            <%= @member.personal_class %>
          </p>

          <strong><%= t 'activerecord.attributes.member.class_promotion_date' %></strong>
          <p class="text-muted">
            <%= @member.class_promotion_date %>
          </p>

          <strong><%= t 'activerecord.attributes.member.practice_level' %></strong>
          <p class="text-muted">
            <%= @member.practice_level %>
          </p>

          <strong><%= t 'activerecord.attributes.member.level_start_date' %></strong>
          <p class="text-muted">
            <%= @member.level_start_date %>
          </p>

          <!-- <strong><%#= t 'activerecord.attributes.member.pending' %></strong>
          <p class="text-muted">
            <%#= @member.pending %>
          </p> -->

          <strong><%= t 'activerecord.attributes.member.role' %></strong>
          <p class="text-muted">
            <%= get_role(@member.role) %>
          </p>

        <%= render partial: 'admin_partials/show/footer', locals: {edit_path: admin_member_edit_path(@member), back_path: index_active_path}%>