config/routes.rb
Rails.application.routes.draw do

  resources :slides
  get 'styleguide' => 'styleguide#index' if Rails.env.development?
  resources :social_bodies
  resources :social_bodies
  resources :chapters
  resources :fees
  resources :private_informations
  resources :laws
  get 'styleguide' => 'styleguide#index' if Rails.env.development?

  get 'admin_members/show/:id', to: 'admin_members#show', as: 'admin_member_show'
  get 'admin_members/edit/:id', to: 'admin_members#edit', as: 'admin_member_edit'
  get 'admin_members/new', to: 'admin_members#new', as: 'admin_member_new'
  patch 'admin_members/update/:id', to: 'admin_members#update', as: 'admin_update_member'
  post 'admin_members/create', to: 'admin_members#create', as: 'admin_create_member'
  delete 'admin_members/destroy/:id', to: 'admin_members#destroy', as: 'admin_destroy_member'
  get 'admin_members/index_pending', to: 'admin_members#index_pending', as: 'index_pending'
  get 'admin_members/index_active', to: 'admin_members#index_active', as: 'index_active'

  resources :protocols, only: [:show, :edit]
  resources :categories
  resources :benefits
  resources :abouts
  resources :jobs
  resources :partners
  resources :posts
  as :member do
    patch '/members/confirmation' => 'members/confirmations#update', :via => :patch, :as => :update_member_confirmation
  end

  devise_for :members, controllers: { confirmations: "members/confirmations"}

  get 'general_pages/about', to: 'general_pages#about', as: 'gp_about'
  get 'general_pages/news', to: 'general_pages#news', as: 'gp_news'
  get 'general_pages/benefits', to: 'general_pages#benefits', as: 'gp_benefits'
  get 'general_pages/contact', to: 'general_pages#contact', as: 'gp_contact'
  post 'general_pages/send_contact', to: 'general_pages#send_contact', as: 'gp_send_contact'

  get 'general_pages/partners', to: 'general_pages#partners', as: 'gp_partners'
  get 'general_pages/jobs', to: 'general_pages#jobs', as: 'gp_jobs'

  get 'general_pages/post/:id', to: 'general_pages#post', as: 'gp_post'
  get 'general_pages/job/:id', to: 'general_pages#job', as: 'gp_job'
  get 'general_pages/benefit/:id', to: 'general_pages#benefit', as: 'gp_benefit'
  get 'general_pages/protocol/:id', to: 'general_pages#protocol', as: 'gp_protocol'
  get 'general_pages/statutes', to: 'general_pages#statutes', as: 'gp_statutes'
  get 'general_pages/laws', to: 'general_pages#laws', as: 'gp_laws'
  get 'general_pages/social_bodies', to: 'general_pages#social_bodies', as: 'gp_social_bodies'
  get 'general_pages/private_informations', to: 'general_pages#private_informations', as: 'gp_private_informations'
  get 'general_pages/profile', to: 'general_pages#profile', as: 'gp_profile'
  root 'general_pages#index'

  get 'admin', to: 'admin_members#index_active', as: 'admin_root'

end

app/models/social_body.rb
class SocialBody < ActiveRecord::Base
end

app/controllers/social_bodies_controller.rb
class SocialBodiesController < ApplicationController
  before_action :authenticate_member!

  before_action :authenticate_admin

  before_action :set_social_body, only: [:show, :edit, :update, :destroy]

  # GET /social_bodies
  # GET /social_bodies.json
  def index
    @social_bodies = SocialBody.page(params[:page]).per(30)
  end

  # GET /social_bodies/1
  # GET /social_bodies/1.json
  def show
  end

  # GET /social_bodies/new
  def new
    @social_body = SocialBody.new
  end

  # GET /social_bodies/1/edit
  def edit
  end

  # POST /social_bodies
  # POST /social_bodies.json
  def create
    @social_body = SocialBody.new(social_body_params)

    respond_to do |format|
      if @social_body.save
        format.html { redirect_to @social_body, notice: 'Social body was successfully created.' }
        # format.json { render :show, status: :created, location: @social_body }
      else
        format.html { render :new }
        # format.json { render json: @social_body.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /social_bodies/1
  # PATCH/PUT /social_bodies/1.json
  def update
    respond_to do |format|
      if @social_body.update(social_body_params)
        format.html { redirect_to @social_body, notice: 'Social body was successfully updated.' }
        # format.json { render :show, status: :ok, location: @social_body }
      else
        format.html { render :edit }
        # format.json { render json: @social_body.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /social_bodies/1
  # DELETE /social_bodies/1.json
  def destroy
    @social_body.destroy
    respond_to do |format|
      format.html { redirect_to social_bodies_url, notice: 'Social body was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_social_body
      @social_body = SocialBody.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def social_body_params
      params.require(:social_body).permit(:name, :role, :position)
    end


    def authenticate_admin
      if !current_member.is_admin?
        redirect_to root_path, notice: "You are no admin!"
      else

      end
    end
end

app/helpers/social_bodies_helper.rb
module SocialBodiesHelper
  def get_position(position)
    get_positions[position]
  end


  def get_positions
    positions = [  'Assembleia Geral',
               'Conselho Directivo',
               'Conselho Fiscal'
              ]
  end

  def get_positions_options
    array = []
    i=0
    get_positions.each do |position|
      array.push([position,i])
      i+=1
    end
    array
  end

  def general_assembly
    0
  end

  def governing_board
    1
  end

  def audit_committee
    2
  end

end

app/views/social_bodies/_form.html.erb
<div class="box-body">
  <%= form_for(@social_body) do |f| %>
    <% if @social_body.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@social_body.errors.count, "error") %> prohibited this social_body from being saved:</h2>

        <ul>
        <% @social_body.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :role %><br>
      <%= f.select :role, options_for_select(get_positions_options()), {}, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :position %><br>
      <%= f.text_field :position, class: "form-control"  %>
    </div>

    <div class="box-footer">
      <%= f.submit   class: "btn btn-primary"%>
    </div>
  <% end %>

app/views/social_bodies/edit.html.erb
<%= render partial: 'admin_partials/edit/header', locals: { section_title:  t("controller."+params[:controller]),
                                                  section_sub_title:  t("action."+params[:action]),
                                                  page_title: t("strings.social_body.edit") } %>


<%= render 'form' %>

<%= render partial: 'admin_partials/edit/footer', locals: {object_to_show: @social_body, back_path: social_bodies_path}%>

app/views/social_bodies/index.html.erb
<%= render partial: 'admin_partials/index/header', locals: { section_title:  t("controller."+params[:controller]),
                                                  section_sub_title:  t("action."+params[:action]),
                                                  page_title: t("strings.social_body.listing") ,
                                                  new_path: new_social_body_path,
                                                  new_button_name: t("strings.social_body.new"),
                                                  search_form_path: nil } %>

<%= render "admin_partials/errors/notices" %>

        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <thead>
              <tr>
                <th><%= t 'activerecord.attributes.social_body.name' %></th>
                <th><%= t 'activerecord.attributes.social_body.role' %></th>
                <th><%= t 'activerecord.attributes.social_body.position' %></th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @social_bodies.each do |social_body| %>
                <tr>
                  <td><%= social_body.name %></td>
                  <td><%= get_position(social_body.role) %></td>
                  <td><%= social_body.position %></td>
                  <%= render partial: 'admin_partials/index/buttons', locals: { object: social_body, edit_path: edit_social_body_path(social_body) } %>

                </tr>
              <% end %>
            </tbody>
          </table>
        </div><!-- /.box-body -->

<%= render partial: 'admin_partials/index/footer', locals: { paginate_object: @social_bodies} %>

app/views/social_bodies/new.html.erb
<%= render partial: 'admin_partials/new/header', locals: { section_title:  t("controller."+params[:controller]),
                                                  section_sub_title:  t("action."+params[:action]),
                                                  page_title: t("strings.social_body.new")  } %>


<%= render 'form' %>

<%= render partial: 'admin_partials/new/footer', locals: {back_path: social_bodies_path}%>

app/views/social_bodies/show.html.erb
<%= render partial: 'admin_partials/show/header', locals: { section_title:  t("controller."+params[:controller]),
                                                  section_sub_title:  t("action."+params[:action]),
                                                  page_title: t("strings.social_body.show")  } %>

<%= render "admin_partials/errors/notices" %>


          <strong><%= t 'activerecord.attributes.social_body.name' %></strong>
          <p class="text-muted">
            <%= @social_body.name %>
          </p>

          <strong><%= t 'activerecord.attributes.social_body.role' %></strong>
          <p class="text-muted">
            <%= get_position(@social_body.role) %>
          </p>

          <strong><%= t 'activerecord.attributes.social_body.position' %></strong>
          <p class="text-muted">
            <%= @social_body.position %>
          </p>
        </div><!-- /.box-body -->

<%= render partial: 'admin_partials/show/footer', locals: {edit_path: edit_social_body_path(@social_body), back_path: social_bodies_path}%>