config/routes.rb
Rails.application.routes.draw do

  resources :slides
  get 'styleguide' => 'styleguide#index' if Rails.env.development?
  resources :social_bodies
  resources :social_bodies
  resources :chapters
  resources :fees
  resources :private_informations
  resources :laws
  get 'styleguide' => 'styleguide#index' if Rails.env.development?

  get 'admin_members/show/:id', to: 'admin_members#show', as: 'admin_member_show'
  get 'admin_members/edit/:id', to: 'admin_members#edit', as: 'admin_member_edit'
  get 'admin_members/new', to: 'admin_members#new', as: 'admin_member_new'
  patch 'admin_members/update/:id', to: 'admin_members#update', as: 'admin_update_member'
  post 'admin_members/create', to: 'admin_members#create', as: 'admin_create_member'
  delete 'admin_members/destroy/:id', to: 'admin_members#destroy', as: 'admin_destroy_member'
  get 'admin_members/index_pending', to: 'admin_members#index_pending', as: 'index_pending'
  get 'admin_members/index_active', to: 'admin_members#index_active', as: 'index_active'

  resources :protocols, only: [:show, :edit]
  resources :categories
  resources :benefits
  resources :abouts
  resources :jobs
  resources :partners
  resources :posts
  as :member do
    patch '/members/confirmation' => 'members/confirmations#update', :via => :patch, :as => :update_member_confirmation
  end

  devise_for :members, controllers: { confirmations: "members/confirmations"}

  get 'general_pages/about', to: 'general_pages#about', as: 'gp_about'
  get 'general_pages/news', to: 'general_pages#news', as: 'gp_news'
  get 'general_pages/benefits', to: 'general_pages#benefits', as: 'gp_benefits'
  get 'general_pages/contact', to: 'general_pages#contact', as: 'gp_contact'
  post 'general_pages/send_contact', to: 'general_pages#send_contact', as: 'gp_send_contact'

  get 'general_pages/partners', to: 'general_pages#partners', as: 'gp_partners'
  get 'general_pages/jobs', to: 'general_pages#jobs', as: 'gp_jobs'

  get 'general_pages/post/:id', to: 'general_pages#post', as: 'gp_post'
  get 'general_pages/job/:id', to: 'general_pages#job', as: 'gp_job'
  get 'general_pages/benefit/:id', to: 'general_pages#benefit', as: 'gp_benefit'
  get 'general_pages/protocol/:id', to: 'general_pages#protocol', as: 'gp_protocol'
  get 'general_pages/statutes', to: 'general_pages#statutes', as: 'gp_statutes'
  get 'general_pages/laws', to: 'general_pages#laws', as: 'gp_laws'
  get 'general_pages/social_bodies', to: 'general_pages#social_bodies', as: 'gp_social_bodies'
  get 'general_pages/private_informations', to: 'general_pages#private_informations', as: 'gp_private_informations'
  get 'general_pages/profile', to: 'general_pages#profile', as: 'gp_profile'
  root 'general_pages#index'

  get 'admin', to: 'admin_members#index_active', as: 'admin_root'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name

  has_many :benefits
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authenticate_member!

  before_action :authenticate_admin


  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.page(params[:page]).per(30)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        # format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        # format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        # format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        # format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end

    def authenticate_admin
      if !current_member.is_admin?
        redirect_to root_path, notice: "You are no admin!"
      else

      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="box-body">
  <%= form_for(@category) do |f| %>
    <% if @category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@category.errors.count, "error") %>  impediram esta categoria de ser guardada:</h2>

        <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="box-footer">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/categories/edit.html.erb
<%= render partial: 'admin_partials/edit/header', locals: { section_title:  t("controller."+params[:controller]),
                                                  section_sub_title:  t("action."+params[:action]),
                                                  page_title: t("strings.category.edit") } %>


<%= render 'form' %>

<%= render partial: 'admin_partials/edit/footer', locals: {object_to_show: @category, back_path: categories_path}%>

app/views/categories/index.html.erb
<%= render partial: 'admin_partials/index/header', locals: { section_title:  t("controller."+params[:controller]),
                                                  section_sub_title:  t("action."+params[:action]),
                                                  page_title: t("strings.categorys.listing") ,
                                                  new_path: new_category_path,
                                                  new_button_name: t("strings.category.new"),
                                                  search_form_path: nil } %>

<%= render "admin_partials/errors/notices" %>

        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <thead>
              <tr>
                <th><%= t 'activerecord.attributes.category.name' %></th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @categories.each do |category| %>
                <tr>
                  <td><%= category.name %></td>
                  <%= render partial: 'admin_partials/index/buttons', locals: { object: category, edit_path: edit_category_path(category) } %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div><!-- /.box-body -->

<%= render partial: 'admin_partials/index/footer', locals: { paginate_object: @categories} %>

app/views/categories/new.html.erb
<%= render partial: 'admin_partials/new/header', locals: { section_title:  t("controller."+params[:controller]),
                                                  section_sub_title:  t("action."+params[:action]),
                                                  page_title: t("strings.category.new")  } %>


<%= render 'form' %>


<%= render partial: 'admin_partials/new/footer', locals: {back_path: categories_path}%>

app/views/categories/show.html.erb
<%= render partial: 'admin_partials/show/header', locals: { section_title:  t("controller."+params[:controller]),
                                                  section_sub_title:  t("action."+params[:action]),
                                                  page_title: t("strings.category.show")  } %>

<%= render "admin_partials/errors/notices" %>
          <strong><%= t 'activerecord.attributes.category.name' %></strong>
          <p class="text-muted">
            <%= @category.name %>
          </p>

<%= render partial: 'admin_partials/show/footer', locals: {edit_path: edit_category_path(@category), back_path: categories_path}%>